/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetNextbus200ApproachinfoItem } from './getNextbus200ApproachinfoItem';

export type GetNextbus200 = {
  approachinfo?: GetNextbus200ApproachinfoItem[];
};
