/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */

export type GetNextbus200ApproachinfoItem = {
  /** 後どれくらいで到着するか */
  more_min?: string;
  /** 到着時刻 */
  real_arrival_time?: string;
  /** バスの方向 */
  direction?: string;
  /** 定時運行かを示す(kicVerではレガシー) */
  delay?: string;
  /** バスの名前 */
  bus_name?: string;
  /** 定時の到着時刻 */
  scheduled_time?: string;
  /** バス停の情報 */
  bus_stop?: string;
  /** 目的地までの所要時間 */
  required_time?: number;
};
