/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetable200HolidayHourItem } from './getTimetable200HolidayHourItem';

export type GetTimetable200Holiday = {
  hour?: GetTimetable200HolidayHourItem[];
};
