/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetableMulti200Timetable立命館大学 } from './getTimetableMulti200Timetable立命館大学';

export type GetTimetableMulti200Timetable = {
  立命館大学?: GetTimetableMulti200Timetable立命館大学;
};
