/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetableMulti200Timetable } from './getTimetableMulti200Timetable';

export type GetTimetableMulti200 = {
  timetable?: GetTimetableMulti200Timetable;
};
