/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */

export type GetTimetableMulti200Timetable立命館大学HolidayHourItem = {
  /** バスの名前 */
  bus_name?: string;
  /** 到着時刻の分 */
  min?: string;
  /** 乗り場 */
  bus_stop?: string;
};
