/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetable200WeekdaysHourItem } from './getTimetable200WeekdaysHourItem';

export type GetTimetable200Weekdays = {
  hour?: GetTimetable200WeekdaysHourItem[];
};
