/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetableMulti200Timetable立命館大学WeekdaysHourItem } from './getTimetableMulti200Timetable立命館大学WeekdaysHourItem';

export type GetTimetableMulti200Timetable立命館大学Weekdays = {
  hour?: GetTimetableMulti200Timetable立命館大学WeekdaysHourItem[];
};
