/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetableMulti200Timetable立命館大学Weekdays } from './getTimetableMulti200Timetable立命館大学Weekdays';
import type { GetTimetableMulti200Timetable立命館大学Holiday } from './getTimetableMulti200Timetable立命館大学Holiday';

export type GetTimetableMulti200Timetable立命館大学 = {
  weekdays?: GetTimetableMulti200Timetable立命館大学Weekdays;
  holiday?: GetTimetableMulti200Timetable立命館大学Holiday;
};
