/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * busdes kic API
 * This is busdes kic API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimetable200Weekdays } from './getTimetable200Weekdays';
import type { GetTimetable200Holiday } from './getTimetable200Holiday';

export type GetTimetable200 = {
  weekdays?: GetTimetable200Weekdays;
  holiday?: GetTimetable200Holiday;
};
