/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  useBusdesKicApIContext,
  BusdesKicApIContext,
} from "./busdesKicApIContext";
import type * as Fetcher from "./busdesKicApIFetcher";
import { busdesKicApIFetch } from "./busdesKicApIFetcher";

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
