/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Timetable = {
  fr: void;
  /**
   * Bus stop to get off
   */
  to: void;
};

export type Nextbus = {
  fr: void;
  /**
   * Bus stop to get off
   */
  to: void;
};
